### ISSUE TITLE
How do I know which part of the game it is?

### ISSUE THREAD

**Issue by rpalmon** [togenyan/Yo-kai_Editor_3#1]
Hello, I want to change the yo-kai on my team but I don't know how to tell which part it is. I want to do Nate's story and Inaho's story but I can't tell the difference. Can you explain it to me?

**Comment by togenyan** [comment]
Hi,
There are two Yo-kai list; section 10 and 31. The list stored in section 10 is for Nate, and the list in section 31 is for Inaho. These lists contain the "num1" and "num2" parameters of each Yo-kai.
![id](https://cloud.githubusercontent.com/assets/17331179/17075555/c157da3e-50d1-11e6-8c92-9d40d968f580.png)
