### ISSUE TITLE
妖怪メダルの所持枠変更をメニューに追加いただくことは可能でしょうか？

### ISSUE THREAD

**Issue by shigerukk** [togenyan/Yo-kai_Editor_3#10]
すごく便利なツールを作成・提供いただきまして、本当にありがとうございます。
セーブエディター２と併用して使用しておりますが、自分でチートコードなどの作成ができないので本当に助かっております。
妖怪メダルの所持枠が、現在配信されている６１８匹より少なく、現在ストーリーの１０章までクリヤーしたのですが、６００です。オークションで販売されているデータをみると、最大６５０まで増やせるようですが、自力で改造コードの作成や検索でも見つけることができず、次回のバージョンアップの際に可能であればメニューに追加いただけないでしょうか？
お忙しいことと存じますが、よろしくお願いいたします。

**Comment by togenyan** [comment]
セーブデータ中の妖怪用の領域(セクション7)が0xD740バイトで，妖怪1体のデータは0x54バイトなので，最大656体の妖怪が格納可能です．
そして，セクション1の0x288に，その内部的な最大値(656)から所有可能数をいくつ減じるか，が格納されています．
例えば，0x288の値が0xFFならば，妖怪の所有最大数は656-255=401となります．0x00ならば，656-0=656で，656体になります．
セクション1の0x288の値は，予約されている妖怪の枠の数，だと思います．この枠の数を減らせば持てる妖怪の数は増えますが，将来的に妖怪の強制加入イベントなどがあった場合に問題が生じることが予想されます．

なお，次のバージョンでこの枠の数の編集機能を追加するつもりです．

**Comment by shigerukk** [comment]
お忙しい中　とても親切に解説いただきまして、本当にありがとうございました。
次のバージョンも楽しみにしておりますので、よろしくお願いいたします。

**Comment by togenyan** [comment]
version 0.4.1 で追加されました．
