### ISSUE TITLE
妖怪管理エリアの自動番付は可能ですか？

### ISSUE THREAD

**Issue by 2016HIROSI** [togenyan/Yo-kai_Editor_3#11]
妖怪編集の自動番付を利用した時に17680付近からの妖怪管理エリアも自動番付のように更新できませんか？
自動番付はとても便利な機能なのですが、適用するとエディターで見えて、ゲーム内で見えない妖怪が出来ます。バトルメンバーの入れ替わりなど発生すると思いますが、17680付近からの妖怪管理エリアも自動番付で更新して頂ければ、エディターで見えて、ゲーム内で見えない妖怪がなくなると思いますのでご検討よろしくお願いします。

**Comment by togenyan** [comment]
> 17680付近からの
セーブデータ上での絶対位置はセーブするたびに変わりうるので，いつもその付近に番号一覧があるわけではありません．おそらくセクション10のことだと思います．バイナリエディタを開いて，右にあるセクション一覧のセクション8の下にありますので確認してください．

> 妖怪管理エリアも自動番付で更新
その機能は既に実装してあるのですが，いまのところ無効化されています(妖怪一覧更新ボタン)．
これは，男主人公の妖怪一覧(セクション10)と女主人公の妖怪一覧(セクション31)が分かれていて，一筋縄では処理できないからです．ストーリーが進んで，2主人公の妖怪メダルが統合されたあとはセクション10のみが使われるようになります．そこで，この機能は統合以降のみに使うべきもの注記を付けて有効化しました (3fd1469)．

**Comment by togenyan** [comment]
version 0.4.2 で追加されました。
