### ISSUE TITLE
生き物図鑑、

### ISSUE THREAD

**Issue by koinj** [togenyan/Yo-kai_Editor_3#12]
生き物図鑑を全開にすることは可能でしょうか？
よろしくお願い致します。

**Comment by togenyan** [comment]
生き物図鑑に登録されているかどうかは，その虫や魚がどうぐの中にあるかどうかで判定されます．(虫や魚は，ジャングルポイントに交換するなどして個数が0になっても項目が残ります)
よって，どうぐに全ての虫・魚を追加すれば生き物図鑑は全開になるはずです(個数は0でもよい)．ただ，一括で一気に追加すると，トロフィーがもらえないようです．少しずつ虫や魚を追加することをおすすめします．

全開にする機能を付けるかどうかは．その実現可能性も含めて検討中です．
