### ISSUE TITLE
スクラッチと戦闘後の友達になることについて

### ISSUE THREAD

**Issue by johndoe1994** [togenyan/Yo-kai_Editor_3#13]
突然で申し訳ないありません

スクラッチの削る所が全て見えるようになるコードと戦闘後、敵妖怪が友達になるコード、もしくは改造できる箇所を教えて頂きたく、自分勝手ながら、送らせて頂きました

もしお教え頂けるなら、お返事をお願いします

本当に、自分の都合で申し訳ありません

**Comment by togenyan** [comment]
アプリケーションに直接関係のない話題はここではなく，メールでお願いします．

**Comment by johndoe1994** [comment]
$B%9%/%i%C%A$N:o$k=j$,A4$F8+$($k$h$&$K$J$k%3!<%I$H@oF.8e!"E(ME2x$,M'C#$K$J$k%3!<%I!"$b$7$/$O2~B$$G$-$k2U=j$r65$($F2<$5$$(B

$B$*4j$$?=$7>e$2$^$9(B

**Comment by togenyan** [comment]
GitHubのissuesにメール経由で投稿なさっているようですが，そうではなくて，私のメールアドレスに直接メールを送ってほしいのです．メールアドレスはYo-kai Editor 3のメニュー，ヘルプ→このアプリケーションについてをご参照ください．
返信が(文字化けしていますが)GitHubのissuesに追加されてしまっています．
https://github.com/togenyan/Yo-kai_Editor_3/issues/13

**Comment by johndoe1994** [comment]
申し訳ありません

メールアドレスを見つけることができませんでした
本当に申し訳ありませんが、教えて頂きたく思います
お願いします
