### ISSUE TITLE
Yo-kai Editor 3　についての要望

### ISSUE THREAD

**Issue by johndoe1994** [togenyan/Yo-kai_Editor_3#14]
何度も申し訳ありません。

Yo-kai Editor 3のことについて、メールさせていただきました。

勝手ながら、必ず友達になる事とスクラッチを全部見えるようにプログラミングするのは、可能でしょうか？
もし、可能であるならば、ぜひともお願いします。

p,s メールアドレスを発見できませんでしたので、教えてくださると幸いです

**Comment by togenyan** [comment]
「Yo-kai Editor 3のことについて」とのことなので，お答えします．
>必ず友達になる事とスクラッチを全部見えるよう

これは，セーブデータ編集で実現できる範囲を超えていると思います．よって，Yo-kai Editor 3にそのような機能が実装されることはないと考えてください．

私ならプログラムコードを書き換えて実現しますが，それはまた別の話です．

>p,s メールアドレスを発見できませんでしたので、教えてくださると幸いです

前にも書きましたが，私のメールアドレスはYo-kai Editor 3のメニューで，「ヘルプ」→「このアプリケーションについて」で開くダイアログボックスに表示されます．
