### ISSUE TITLE
連動妖怪について

### ISSUE THREAD

**Issue by koinj** [togenyan/Yo-kai_Editor_3#19]
連動妖怪と戦えるようになるフラグを立てることは可能でしょうか？
（天コマ、すしジバ、ぷににゃん等）

**Comment by togenyan** [comment]
#7 で既に同様の質問にお答えしていますが、もう一度まとめておきます。

ぷにニャン・ぷにコマ・スシジバ・天コマを登場させるフラグはセーブデータに存在します。
ただし、このフラグを有効にしただけでは、これらの妖怪に話しかけると「権利がない」と言われ、バトルはできません。実際にバトルをするためには、その3DSに追加コンテンツがインストールされている必要があります。
追加コンテンツとは、他のゲームでいうDLCのことです。妖怪ウォッチ3では、このDLCがダウンロード番号で「購入」できるようになっています。せんぷうコイン・ダウンロード版特典・ぷにぷにの特典は全てDLCで提供されています。
よって、セーブデータ編集だけではこれらの妖怪とバトルすることはできません。

ちなみに、DLCは「タイトル」の形式をとります。全てのDLCコンテンツは一つのタイトルに集約されています。
参考: https://www.3dbrew.org/wiki/Title_list/DLC
