### ISSUE TITLE
[Suggestion] Add separate YOKAI Tab under female tab

### ISSUE THREAD

**Issue by rpalmon** [togenyan/Yo-kai_Editor_3#2]
Hello, I think that as an update that can be for version 4.0, I think you can make a separate  YOKAI tab under the female tab. You told me that under section 10 is stored for Nate and under section 31 is stored for Inaho. Why not make it accessible to anyone to make it easy to change the Yo-Kai based on which tab it is. I think that it would really help. You could just make a code that corresponds Nate and section 10 and Inaho and section 31 to change the Yo-Kai. Can you do it?

**Comment by togenyan** [comment]
Thank you for your suggestion but I have no plan for separating the Yo-kai tab.
Reasons:
1) This application is designed to show the structure of save data as they're stored. The Yo-kai data is stored in one place (section 7) and not separated.
2) Yo-kai medallium and items get integrated after you beat chapter 5.
