### ISSUE TITLE
スポーツクラブのHPについて

### ISSUE THREAD

**Issue by maruchina** [togenyan/Yo-kai_Editor_3#20]
スポーツクラブのHPの修正可能な上限が他のステータスと同じく25になっていますが50ではないでしょうか？
間違えていたらすみません。

**Comment by togenyan** [comment]
スポーツクラブの補正値は、HP含め全て
-(トレーニング回数 * 2) <= 補正値 <= トレーニング回数 * 5
でなければなりません。よって、-10から25までで合っています。
25を超える値に設定したとしても反映されないはずです。
(もしできたら教えてください)
