### ISSUE TITLE
スキヤキへの対応を楽しみにしております

### ISSUE THREAD

**Issue by shigerukk** [togenyan/Yo-kai_Editor_3#23]
スキヤキへの対応を楽しみにしておりますので、よろしくお願いいたします

**Comment by togenyan** [comment]
version 0.6を試してみてください。
もしうまく動かなかったら教えてください。

**Comment by 2016HIROSI** [comment]
便利なエディターをありがとうございます。
version 0.6になった時に、うっかりスキヤキも編集してしまいましたが、問題ありませんでしたよ。
スキヤキでも動作良好です。

**Comment by shigerukk** [comment]
お忙しい中　スキヤキのご対応いただきまして、本当にありがとうございました。
早速活用させていただいております。よろしくお願いいたします。

**Comment by togenyan** [comment]
表題の件は済んだのでcloseします。
また何かありましたら新しいissueを立ち上げてください。
