### ISSUE TITLE
ＩＤについて

### ISSUE THREAD

**Issue by yo-kai** [togenyan/Yo-kai_Editor_3#24]
ミーフー、ぬらりひょん、トリベア、自慢ハッタンのIDあってますか？
ゲーム内に出てこなかったもので。確認お願いします。

**Comment by korozo** [comment]
こちらは問題なかったんです、全部出ました。
スシ2.0です

**Comment by yo-kai** [comment]
返信ありがとうございます
テンプラなんですけどyoukai.xmlの中の<item id="1009069976" index="651" name="ぬらりひょん" />を自分で変換してセーブエディタ2のアドバンスで書き換えたんですけど出てこなかったんですよ
ぬらりひょん982Ｆ253Ｃ　
トリベアC9D1B459
自慢ハッタン 1409DEAB
ミーフー57Ｅ38105　　　　　これ間違ってます？

**Comment by togenyan** [comment]
korozo さん
動作検証ありがとうございます。ほとんどテストできていないので助かります。

yo-kai さん
このページではYo-kai Editor 3に関係のない問題については取り扱いません。
もしYo-kai Editor 3を使って問題が生じているなら、操作内容を詳しく説明してください。

**Comment by yo-kai** [comment]
妖怪のIDあっていました。格納番号がおかしくなっていて4体が表示されていないだけでした。

スキヤキでも動く気がしますってなっていましたので動作検証したところ私の環境では妖怪の変更は問題なくできますが、Tトレのアイテムを弄るとセーブデーターが破損してしまいます。

**Comment by togenyan** [comment]
バスターズのアイテムボックスにアイテムを追加してみましたが、正常に動作しました(スキヤキ、JKSV利用)。
番号や位置、強化値が適切であることを確認し、やり直してみてください。
それでも駄目なら、セーブデータを私にメールか何かで送ってください。調査します。ただし必ず解決することは保証できませんのでご了承ください。

**Comment by yo-kai** [comment]
たぶんですけど破損になっていた原因がわかりました。
バスターズトレジャーのそうび欄の上から5番目がFF FE DD 08 FE FF 46 08 30 30を参照しているみたいです。
この5番目を盾のＩＤに書き換えると破損してしまいます。

**Comment by togenyan** [comment]
検証ありがとうございます。どうやらセクション38と48に分かれているのを無視していたようです。
次のバージョンで修正したいと思います。

**Comment by togenyan** [comment]
ひとまず問題は解決したのでcloseします。
また何かありましたら新しいissueを立ち上げてください。
