### ISSUE TITLE
エラー(401)

### ISSUE THREAD

**Issue by pyontan** [togenyan/Yo-kai_Editor_3#25]
妖怪ウォッチ3 テンプラをVer2.0にアップデート後、
2.0にアップデートしたゲームデータを開こうとすると、
エラー(104)のダイアログが表示され、開けない。
2.0にアップデートしていない方は開ける。
2.0にアップデートしたゲームデータのファイルサイズが、
2KBほど大きくなっている。

**Comment by togenyan** [comment]
まず、Yo-kai Editor 3のバージョンと、読み込んだセーブデータの形式(CYBER セーブエディタなら復号済み、JKSVなどそれ以外なら暗号化されたまま)を教えてください。
また、エラー(104)が表示されるとのことですが、そのようなエラー番号は存在しないはずです。
もう一度確認をお願いします。

> 2.0にアップデートしたゲームデータのファイルサイズが、
> 2KBほど大きくなっている。

それは正常な挙動です。
1.4のgame*.ywは112,620 バイト、2.0のgame*.ywは113,732バイトになるはずです。

**Comment by pyontan** [comment]
ファイルは、CYBER セーブエディタ２の複合済みデータです。
エラーは401の間違いでした。

**Comment by togenyan** [comment]
#26 と同じ問題かもしれません。

エラー番号から推測するに、セーブデータの復号がうまくいっていない可能性があります。
CYBER セーブエディタはときどきセーブデータの復号に失敗することがあるので、アドバンスモードを開いたときに復号されているかどうか確認してみてください。セーブデータが正常に復号されていれば、
`00000020 FE FF 00 00 F1 ...`
という行があるはずです。

**Comment by pyontan** [comment]
回答ありがとうございます。
すし、てんぷらとも正常に復号が出来ないみたいです。
「00000020 FE FF 00 00 F1 ...」がありませんでした。
CYBER セーブエディタの方の問題と思われますので、
本質問についてはクローズします。
