### ISSUE TITLE
エラー203-401

### ISSUE THREAD

**Issue by peacemark** [togenyan/Yo-kai_Editor_3#28]
他の方も書かれて居るのですが、こちらのエラー「203-401」の場合エディターの複合エラーではなく、セーブデータが2つある場合のみエラーが出る気がします。
日記1がバージョン2.0のセーブと日記2が1.4のセーブがあった場合2.0はエラー203-401が出るのですが1.4の場合は普通に編集出来ました。
そして日記を2つとも2.0にしたところ2つともエラー203-401になりました。
再度日記を書き直してもやはりエラー203-401が出て編集出来ませんでした。
日記が2つあるとエラーがあるということで何か複合に変化があるのでないでしょうか？
確認できる環境ではないため、出来ましたら確認と更新の方をどうか宜しくお願い申し上げます。

**Comment by togenyan** [comment]
確認してみたところ、確かにYo-kai Editor 3 においてもセーブデータの復号に失敗することがありました。
鍵の計算に使う値が異なるために、誤った鍵が計算されるようです。もう少し検証してみます。

**Comment by togenyan** [comment]
* homebrewなどで暗号化されたセーブデータを抽出している場合
セーブデータが2つある場合に一方だけ復号できないことがありました。
これは、異なるセーブデータが異なる鍵を使うことによるものです。その場しのぎ的な解決策ではありますが、修正しました。なお、この問題はCYBERセーブエディターで復号する際は生じません。

* CYBER セーブエディターを利用して復号されたセーブデータを抽出している場合
アドバンスモードで正常に復号されたデータが表示されないのは、CYBER セーブエディターの問題であり、当然ながら当アプリケーションは関係ありません。上の問題とは別のものとお考えください。

**Comment by peacemark** [comment]
お忙しい中ご検証ありがとうございます。
当方理解致しました。
こちらのツールはとても感謝しております。
これからも応援しております。
