### ISSUE TITLE
Linking Items Not Working? (Sukiyaki 2.3 JP)

### ISSUE THREAD

**Issue by PolarPeridot** [togenyan/Yo-kai_Editor_3#34]
Hi! So I added all the linking items there are in the game (The Sushi Pillow for Sushijiba, the Tempura Pouch for Tenkoma, the Ganso Bell for Jibanyan S, the Honke Pouch for Komasan S, the Shin'uchi Pouch for Komajiro S, the Puni Egg for Tamago no Kimi, the Punipuni Orb for Puninyan and Punikoma, the Red Cat Membership Card and White Dog Membership Card for B Jibanyan, B Komasan, and B USApyon, and the Oomaru Momoman for the Sangokushi Yo-Kai.) but whenever I go the the places said Yo-Kai should appear, they don't show up. Please help me figure out why? I really want to get these Yo-Kai but I can't link the games together.

**Comment by togenyan** [comment]
(related issues: #7 and #19)
> Please help me figure out why?

To make them appear in the game, you need another steps.

### DLC Yo-kai
To befriend Tamago no Kimi, Puninyan, Punikoma, Sushijiba, Tenkoma, and USAdofu, you need to have the title 0004008c00191000 installed. To make the title loaded correctly you might need to set the region and language of the console to `JPN/JA`. (Luma3DS will work)

### Other Yo-kai (http://www.youkai-watch.jp/yw3/rendou/)
Change the values at 0x19, 0x1A of the section 1 as following:
```
00 00 → F0 03
```
(tested on Tempura, but should work on other versions)

**Comment by PolarPeridot** [comment]
By Section 1, does that mean the section labeled 241?

**Comment by PolarPeridot** [comment]
Is this the areas you are referring to? http://prntscr.com/esrk8x

**Comment by togenyan** [comment]
No.
![t](https://cloud.githubusercontent.com/assets/17331179/24779780/6140a40c-1b6d-11e7-81a5-bce5ce6bd76b.png)

**Comment by PolarPeridot** [comment]
Ahh, I see! Thank you so much!
