### ISSUE TITLE
Mac版Ver.0.6.4以降、利用できません。

### ISSUE THREAD

**Issue by alt0829** [togenyan/Yo-kai_Editor_3#35]
Mac版のyokai editorを使用しています。
0.6.3までは問題なく利用できましたが、0.6.4以降は利用できなくなりました。
アプリを実行しても「予期しない理由で終了しました」と表示されます。

0.6.4以降はQt5.8を使用してビルドしています、と記載がありましたが、何か事前にインストール等が必要なのでしょうか？
OSは最新の10.12.4を使用しています。

お手数おかけしますが、ご回答よろしくお願いします。

**Comment by togenyan** [comment]
> 0.6.4以降はQt5.8を使用してビルドしています、と記載がありましたが、何か事前にインストール等が必要なのでしょうか？

いいえ。リリースにあるビルドを実行するのには何もインストールする必要はありません。
手元にmacOS 10.12の環境がないため、検証できていませんでしたが、ビルド環境が変わったために問題が生じたと考えられます。
アプリケーションが終了したあとに表示されるダイアログで、「レポート」をクリックすると、問題の詳細が表示されますので、その内容を教えてください（ここに貼り付けるか、メールしてください）。

**Comment by alt0829** [comment]
返信ありがとうございます。
レポート内容ですが、エラー項目が多いので添付します。
[20170415.txt](https://github.com/togenyan/Yo-kai_Editor_3/files/923375/20170415.txt)

お手数おかけしますが、ご確認お願いします。

**Comment by togenyan** [comment]
ご報告ありがとうございます。調査の結果、実行に必要な一部のファイル(Qtのプラグイン)がアプリケーションバンドル内にコピーされていないことが分かりました。修正したものをReleaseページにアップロードしましたので、試してみてください。

**Comment by alt0829** [comment]
迅速なご対応ありがとうございます。
正常に起動することを確認しました。

まだ動作確認までは終えていませんが、何か問題がありましたら改めてご報告させていただきます。
この度はどうもありがとうございました。
