### ISSUE TITLE
妖怪の所持数について

### ISSUE THREAD

**Issue by keishinh** [togenyan/Yo-kai_Editor_3#36]
togenyan様
Yo-kai_Editor_3、いつも快適に使わせていただいております、ありがとうございます。

ところで、質問なのですが、
妖怪の所持数の上限を増やすことはできますか？
よろしくお願いします。

**Comment by yo-kai** [comment]
かなり前のVerから実装してるじゃん

**Comment by togenyan** [comment]
keishinh さん

#10 をご覧ください。なお、この機能は
共通>情報1>予約された大辞典の枠の数
にあります。

**Comment by keishinh** [comment]
yo-kai様、togenyan様

お返事ありがとうございます。
あまり使いこなしていなかったというか、Issuesもきちんと見ておくべきでした。
これで所持数上限を増やせそうです。
ありがとうございました！
