### ISSUE TITLE
Two Questions

### ISSUE THREAD

**Issue by Yo-Cookie** [togenyan/Yo-kai_Editor_3#37]
1.How do you translate the Yo-Kai Watch 3 editor to english?
2.How do I find the option to unlock all my nyan items?
I heard you have download some thing called "Yo-Kai Watch 3 Editor Pro.
If That's The Case Then How Do You Download It?

**Comment by togenyan** [comment]
1. It's already translated into English. The app detects the OS locale automatically and uses most suitable one.

2. Open "Info 1" tab. Tick all checkboxes from 85 to 204, then hit the apply button.

![2017-09-03 09 52 29](https://user-images.githubusercontent.com/17331179/29999722-2e15f172-908e-11e7-9265-285f140563ee.png)

**Comment by Yo-Cookie** [comment]
Where Do I Find The OS Locale?

**Comment by togenyan** [comment]
Currently no translations available for names of Yo-kai and items.

**Comment by Yo-Cookie** [comment]
Oh.Okay.Thanks For The Answers!:)
