### ISSUE TITLE
できれば次回作　妖怪ウォッチバスターズ２　対応のeditor　楽しみしております

### ISSUE THREAD

**Issue by shigerukk** [togenyan/Yo-kai_Editor_3#39]
Yo-kai_Editor_3 　アップデートの都度ご対応いただきまして、本当にありがとうございます。
毎回使用させていただいております。

来週　３DS　妖怪ウォッチバスターズ２　のソフトが発売されますが、新しくeditorを作成されましたらぜひ活用させていただきたいと思いますので、お知らせ頂ければ幸いです。

楽しみにしておりますのでいつかよろしくお願いいたします

**Comment by togenyan** [comment]
確実にお約束はできませんが、セーブデータ編集ツールを作成したいとは考えています。
ただし、しばらく開発環境が用意できないため、当面解析、およびアプリケーションの作成はできそうにありません。多少時間はかかるかと思いますが、対応できしだいお知らせします。
(私の公開しているアプリケーションの一覧は、 https://github.com/togenyan/repositories から確認できます)

**Comment by togenyan** [comment]
https://github.com/togenyan/Yo-kai_Editor_B2/releases
