### ISSUE TITLE
Save Error [103]

### ISSUE THREAD

**Issue by rpalmon** [togenyan/Yo-kai_Editor_3#4]
When ever I edit my save and then save it to a folder, I try to open it and it gives me the error 103. Can you fix it? Along with the My Nyan editor in the next update?

**Comment by rpalmon** [comment]
What does the head.yw do? Is it what displays the diary and the levels before opening the save?

**Comment by togenyan** [comment]
head.yw contains the key (more precisely data to generate key, not key itself) to decrypt game*.yw.

**Comment by rpalmon** [comment]
One more thing, in the game there are some quests that require you to be there at a certain time. Do you think that you could have an option in the editor to change the time? Example: There would be a text box and 0:00 would be midnight, 12:00 would be noon (mid day) for presets and you could set custom times such as 6:00 would be at dawn. That would be great.

**Comment by togenyan** [comment]
695bda5
