### ISSUE TITLE
[Suggestion] Yo-kai list by number

### ISSUE THREAD

**Issue by GSLinux** [togenyan/Yo-kai_Editor_3#5]
It would make it easier to edit (change) a Yo-kai you have already befriended into another Yo-kai if the Yo-kai selection drop down list had them in numerical order. Adding an index to each Yo-kai name would make searching for them much easier. Either that or a search bar.

**Comment by togenyan** [comment]
added (7ef53c9)
![2016-08-12 10 28 17](https://cloud.githubusercontent.com/assets/17331179/17610316/d325ca4a-6077-11e6-8323-9e060c503277.png)
