### ISSUE TITLE
レジェンド妖怪の再解放

### ISSUE THREAD

**Issue by johndoe1994** [togenyan/Yo-kai_Editor_3#6]
突然で申し訳ありません。

Yo-kai Editor 3のことについて、メールさせていただきました。

勝手ながら、レジェンド妖怪を再解放できるようにプログラミングするのは、可能でしょうか？
もし、可能であるならば、ぜひともお願いします。

最後に、個人的わがままを作者さまに送らせていただいたことをお詫び申し上げます

**Comment by togenyan** [comment]
レジェンド妖怪解放済みのフラグはセクション1の0xA8Cと0xA8Dにあります．
0xA8C: 0ビット目 ブシニャン, 1ビット目 しゅらコマ，... , 7ビット目 やまタン
0xA8D: 0ビット目 ばたんQ, 2ビット目 乙姫(スシのみ), 3ビット目 あしゅら(テンプラのみ)
0xA8Cと0xA8Dに00を書き込めば再度解放できるようになります．

GUIでもリセットできるようにしました(218ba399)．ただ，すぐにはリリースしないので，それまではバイナリエディタ(編集→バイナリエディタで編集)を使って編集してください．

**Comment by johndoe1994** [comment]
$BJV?.$"$j$,$H$&$4$6$$$^$9(B

$B<+J,>!<j$J4uK>$rL5M}6/$$$7$F(B
$BK\Ev$K?=$7Lu$"$j$^$;$s(B

$B:n<TMM$N8f8|0U$rK\Ev$K46<U$7$^$9(B
$B$"$j$,$H$&$4$6$$$^$7$?(B

**Comment by togenyan** [comment]
version 0.4.1 で追加されました．
