### ISSUE TITLE
連動アイテム、ダウンロード特典アイテムの件

### ISSUE THREAD

**Issue by peacemark** [togenyan/Yo-kai_Editor_3#7]
Yo-kai_Editor_3　を開発してくださりまことに感謝しております。

さてこの度連絡しましたのは『連動アイテム、ダウンロード特典アイテムの件』でございます。
だいじなものにアイテムを追加しましてもアイテムを持っておりますがいるはずの妖怪がおりません。

バイナリ等で受け取ったフラグを立てられるのであれば教えていていただければ幸いでございます。

お忙しいとは思いますが、これからも応援しておりますのでお体に気を付け解析等頑張ってください。

**Comment by togenyan** [comment]
まずダウンロード版限定妖怪ですが，おそらく追加データを編集する必要があるのでこのアプリケーションでは無理です．(セーブエディターでも無理です．CFWを導入した3DSが必要)
連動特典の妖怪は簡単で，セクション1の0x19, 0x1Aを次のように変更すればよいです．
```
19 1A | 00 00
↓
19 1A | F0 03
```
これで6ビット立ちます．妖怪ウォッチ2の3本，バスターズ2本，三国志に対応しているはずです．

**Comment by peacemark** [comment]
ご連絡ありがとうございます。

素人の私には少しレベルが高いようですがCFWの3DSがありますので、頑張ってやってみたいと思います。

お忙しい中ご連絡ありがとうございました。
これからも応援しております。

**Comment by togenyan** [comment]
いまさらですが、ダウンロード版限定妖怪、および妖怪ウォッチぷにぷにの特典を有効にするのもセーブデータの編集で十分なようです。
